# Generated by Django 4.2.30 on 2026-07-15 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comprobantes', '0002_alter_logenviosunat_codigo_respuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='detallecomprobante',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='detallecomprobante',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='detallecomprobante',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='detallecomprobante',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='logenviosunat',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='logenviosunat',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='logenviosunat',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='logenviosunat',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
