# Generated by Django 4.2.30 on 2026-07-15 22:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='seriecomprobante',
            name='serie',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]\\w{3}$', 'La serie debe ser una letra seguida de 3 caracteres (ej: F001).')], verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='seriecomprobante',
            name='tipo',
            field=models.CharField(choices=[('F', 'Factura'), ('B', 'Boleta'), ('FC', 'Nota de Crédito (Factura)'), ('BC', 'Nota de Crédito (Boleta)')], max_length=2, verbose_name='Tipo de Comprobante'),
        ),
    ]
